from rest_framework.authtoken.views import ObtainAuthToken
from django.urls import path
from .views import (
    ItemCreateView,
    ItemDetails,
    FlightResponse,
    HomeView,
    PostCreateView,
    PostView,
    PopularDestinationView,
    PopularDestinationDetails,
    FlightsView,
    CityAutocomplete,
    GetLocationId,
    GetRestaurants,
    UserRegistrationView,
    TokenAuthenticationView,
    UserLogoutView,
    UserPostView,
    PostCommentsView,
    PostCommentsDetail,
    UserPostDetailsView,
    GetUserIDView,
    CommentsDetails,
    LikesView,
    PostLikesView,
    DeleteLikesView,
    FlightsView
)

urlpatterns = [
    path("", HomeView.as_view()),
    path("items", ItemCreateView.as_view()),
    path("items/<str:pk>", ItemDetails.as_view()),
    path("posts", UserPostView.as_view()),
    path("posts/<str:pk>", UserPostDetailsView.as_view()),
    path("popular_destinations", PopularDestinationView.as_view()),
    path("popular_destinations/<str:pk>", PopularDestinationDetails.as_view()),
    path("flights", FlightsView.as_view()),
    path(
        "cities/autocomplete/<str:city>",
        CityAutocomplete.as_view(),
        name="city-autocomplete",
    ),
    path("location/<str:keyword>", GetLocationId.as_view(), name="get-locationId"),
    path("restaurants/<str:locationId>", GetRestaurants.as_view(), name="restaurants"),
    path("auth/signup", UserRegistrationView.as_view()),
    path("auth/login", ObtainAuthToken.as_view()),
    path("auth/verify", TokenAuthenticationView.as_view()),
    path("auth/logout", UserLogoutView.as_view()),
    # path(
    #     "flights/<str:travel_type>/<str:dept>/<str:arr>/<str:date>/<int:adult_no>/<int:child_no>/<int:infant_no>/<str:cabin_class>/<str:currency>",
    #     FlightResponse.as_view(),
    # ),
    path("flights/<str:departure>/<str:arrival>/<str:date>",FlightsView.as_view()),
    path("comments", PostCommentsView.as_view()),
    path("comments/<str:post>", PostCommentsDetail.as_view()),
    path("comments/delete/<str:pk>",CommentsDetails.as_view()),
    path("users/<str:username>",GetUserIDView.as_view()),
    path("likes",LikesView.as_view()),
    path("likes/delete/<str:pk>",DeleteLikesView.as_view()),
    path("likes/<str:post>",PostLikesView.as_view())
]
